// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/HoronLee/EchoHub/internal/config"
	"github.com/HoronLee/EchoHub/internal/data"
	"github.com/HoronLee/EchoHub/internal/handler"
	"github.com/HoronLee/EchoHub/internal/server"
	"github.com/HoronLee/EchoHub/internal/service"
	"github.com/HoronLee/EchoHub/internal/util/log"
	"github.com/HoronLee/EchoHub/internal/validator"
)

// Injectors from wire.go:

// InitServer 初始化服务器
func InitServer(cfg *config.AppConfig) (*server.HTTPServer, func(), error) {
	logger := log.NewLogger(cfg)
	db, err := data.NewDB(cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	helloWorldRepo := data.NewHelloWorldRepo(dataData, logger)
	helloWorldService := service.NewHelloWorldService(helloWorldRepo)
	helloWorldHandler := handler.NewHelloWorldHandler(helloWorldService)
	userRepo := data.NewUserRepo(dataData, logger)
	userService := service.NewUserService(userRepo)
	validatorValidator := validator.NewValidator(cfg)
	userHandler := handler.NewUserHandler(userService, validatorValidator)
	handlers := handler.NewHandlers(helloWorldHandler, userHandler)
	httpServer := server.NewHTTPServer(cfg, handlers, db, logger, validatorValidator)
	return httpServer, func() {
		cleanup()
	}, nil
}
